version: '3'
services:
  db:
    image: postgres
    container_name: exampleproject_postgres
    ports: 
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  pgadmin:
    image: dpage/pgadmin4
    container_name: exampleproject_pgadmin
    ports:
      - 8008:8008
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mycsn.be
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_PORT: 8008
    volumes:
      - /var/lib/pgadmin4/storage
    